/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2024-04-12 10:09:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import businesslayer.SubscriptionBusinessLogic;
import model.Subscription;
import model.PurchasedInventory;
import model.ClaimedInventory;
import model.User;
import businesslayer.InventoryBusinessLogic;
import java.util.List;
import model.Inventory;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(8);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("model.PurchasedInventory");
    _jspx_imports_classes.add("model.User");
    _jspx_imports_classes.add("businesslayer.SubscriptionBusinessLogic");
    _jspx_imports_classes.add("model.Subscription");
    _jspx_imports_classes.add("model.Inventory");
    _jspx_imports_classes.add("model.ClaimedInventory");
    _jspx_imports_classes.add("businesslayer.InventoryBusinessLogic");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;


    if (session == null || session.getAttribute("user") == null) {
        response.sendRedirect("../index.jsp"); // Redirect to the home page
        return; // Stop processing the rest of the JSP
    }

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("               ");
 
                   InventoryBusinessLogic inventoryService = new InventoryBusinessLogic();
                   SubscriptionBusinessLogic subscriptionService = new SubscriptionBusinessLogic();
                   
                   User user = (User)session.getAttribute("user");
                   String userType = user.getUserType();
                   List<Inventory> inventory = inventoryService.getInventory(user); 
                   List<ClaimedInventory> claimedItems = null;
                   if (userType.equalsIgnoreCase("charitable_organization")) {
                        claimedItems = inventoryService.getClaimedItems(user.getId()); 
                   }
                   List<PurchasedInventory> purchasedItems = null;
                   List<Subscription> subscriptions = null;
                   if (userType.equalsIgnoreCase("consumer")) {
                        purchasedItems = inventoryService.getPurchasedItems(user.getId()); 
                        subscriptions = subscriptionService.getSubscriptions(user.getId()); 
                   }
               
      out.write("\r\n");
      out.write("                   \r\n");
      out.write("                    <!DOCTYPE html>\r\n");
      out.write("                    <html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("                    <head>\r\n");
      out.write("                        <title>Food Waste Reduction Platform</title>\r\n");
      out.write("                        <meta charset=\"utf-8\">\r\n");
      out.write("                        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("                        <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css\">\r\n");
      out.write("                        <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js\"></script>\r\n");
      out.write("                        <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("                        <style>\r\n");
      out.write("                            /* Remove the navbar's default margin-bottom and rounded borders */\r\n");
      out.write("                            \r\n");
      out.write("                            .navbar {\r\n");
      out.write("                                margin-bottom: 0;\r\n");
      out.write("                                border-radius: 0;\r\n");
      out.write("                            }\r\n");
      out.write("                            /* Add a gray background color and some padding to the footer */\r\n");
      out.write("                            \r\n");
      out.write("                            footer {\r\n");
      out.write("                                background-color: #f2f2f2;\r\n");
      out.write("                                padding: 25px;\r\n");
      out.write("                            }\r\n");
      out.write("                            \r\n");
      out.write("                            .panel-right {\r\n");
      out.write("                                float: right;\r\n");
      out.write("                            }\r\n");
      out.write("                            \r\n");
      out.write("                            .mt-5 {\r\n");
      out.write("                                margin-top: 50px;\r\n");
      out.write("                            }\r\n");
      out.write("                            .near-expiry-item{\r\n");
      out.write("                                background: #d9534f36;\r\n");
      out.write("                            }\r\n");
      out.write("                        </style>\r\n");
      out.write("                    </head>\r\n");
      out.write("\r\n");
      out.write("                    <body>\r\n");
      out.write("\r\n");
      out.write("                        <nav class=\"navbar navbar-inverse\">\r\n");
      out.write("                            <div class=\"container-fluid\">\r\n");
      out.write("                                <div class=\"navbar-header\">\r\n");
      out.write("                                    <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#myNavbar\">\r\n");
      out.write("                            <span class=\"icon-bar\"></span>\r\n");
      out.write("                            <span class=\"icon-bar\"></span>\r\n");
      out.write("                            <span class=\"icon-bar\"></span>                        \r\n");
      out.write("                          </button>\r\n");
      out.write("                                    <a class=\"navbar-brand\" href=\"#\">Food Waste Reduction Platform</a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"collapse navbar-collapse\" id=\"myNavbar\">\r\n");
      out.write("                                    <ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("                                        <li><a href=\"../UserServlet?action=logout\"><span class=\"glyphicon glyphicon-log-out\"></span> Logout</a></li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </nav>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"container mt-5\">\r\n");
      out.write("                            <!-- Inventory Panel -->\r\n");
      out.write("                            <div class=\"panel\">\r\n");
      out.write("                                <div class=\"panel-heading\">\r\n");
      out.write("                                    <div class=\"row\">\r\n");
      out.write("                                        <div class=\"col-sm-8\">\r\n");
      out.write("                                            <h3 class=\"panel-title\"><span class=\"glyphicon glyphicon-th\"></span> Inventory</h3>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"col-sm-4\">\r\n");
      out.write("                                            <button type=\"button\" class=\"btn btn-primary panel-right\" data-toggle=\"modal\" data-target=\"#addInventoryModal\"> <span class=\"glyphicon glyphicon-plus\"></span> Add New</button>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"panel-body\">\r\n");
      out.write("                                    ");
 if (session.getAttribute("success_msg") != null) { 
      out.write("\r\n");
      out.write("                                        <div class=\"alert alert-success\" role=\"alert\">\r\n");
      out.write("                                            ");
      out.print( session.getAttribute("success_msg") );
      out.write("\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    ");
 session.removeAttribute("success_msg"); 
      out.write("\r\n");
      out.write("                                    ");
 } 
      out.write("\r\n");
      out.write("                                    <table class=\"table table-bordered table-striped\">\r\n");
      out.write("                                        <thead>\r\n");
      out.write("                                            <tr>\r\n");
      out.write("                                                <th>Item</th>\r\n");
      out.write("                                                <th>Quantity</th>\r\n");
      out.write("                                                <th>Expiration Date</th>\r\n");
      out.write("                                                <th>Price</th>\r\n");
      out.write("                                                 ");
 if (userType.equalsIgnoreCase("retailer") || userType.equalsIgnoreCase("consumer")) { 
      out.write("\r\n");
      out.write("                                                    <th>Discounted Price</th>\r\n");
      out.write("                                                 ");
 } 
      out.write("\r\n");
      out.write("                                                 ");
 if (userType.equalsIgnoreCase("retailer")) { 
      out.write("\r\n");
      out.write("                                                    <th>Flagged For Surplus</th>\r\n");
      out.write("                                                    <th>Marked for donation</th>\r\n");
      out.write("                                                 ");
 } 
      out.write("\r\n");
      out.write("                                                <th>Actions</th>\r\n");
      out.write("                                            </tr>\r\n");
      out.write("                                        </thead>\r\n");
      out.write("                                        <tbody>\r\n");
      out.write("                                            ");
 
                                            for (Inventory item : inventory) {
                                                // Calculate if the item is surplus
                                                boolean expiresInAweek = false;
                                                if (item.getExpirationDate() != null) {
                                                    java.util.Date today = new java.util.Date();
                                                    long diff = item.getExpirationDate().getTime() - today.getTime();
                                                    long daysUntilExpiration = diff / (24 * 60 * 60 * 1000);
                                                    if (daysUntilExpiration <= 7) {
                                                        expiresInAweek = true;
                                                    }
                                                }
                                            
      out.write("\r\n");
      out.write("                                            <tr id=\"item-");
      out.print( item.getId());
      out.write("\">\r\n");
      out.write("                                                <td>");
      out.print( item.getItemName());
      out.write("</td>\r\n");
      out.write("                                                <td>");
      out.print( item.getQuantity());
      out.write(" \r\n");
      out.write("                                                    <span style=\"float: right;\">\r\n");
      out.write("                                                        <button type=\"button\" class=\"btn btn-success btn-xs\" onclick=\"showAddQuantityModal(");
      out.print( item.getId());
      out.write(',');
      out.write('\'');
      out.print( item.getItemName());
      out.write("')\"> <span class=\"glyphicon glyphicon-plus\"></span></button>     \r\n");
      out.write("                                                    </span>\r\n");
      out.write("                                                </td>\r\n");
      out.write("                                                <td class=\"");
      out.print( expiresInAweek ? "near-expiry-item" : "" );
      out.write('"');
      out.write('>');
      out.print( item.getExpirationDate());
      out.write("</td>\r\n");
      out.write("                                                <td>");
      out.print( item.getPrice());
      out.write("</td>\r\n");
      out.write("                                                 ");
 if (userType.equalsIgnoreCase("retailer") || userType.equalsIgnoreCase("consumer")) { 
      out.write("\r\n");
      out.write("                                                    <td>");
      out.print( item.getDiscount() !=0 ? item.getPrice() - item.getDiscount() : "" );
      out.write("</td>\r\n");
      out.write("                                                 ");
 } 
      out.write("\r\n");
      out.write("                                                 ");
 if (userType.equalsIgnoreCase("retailer")) { 
      out.write("\r\n");
      out.write("                                                    <td>");
      out.print( item.isFlagged() ? "Yes" : "" );
      out.write("</td>\r\n");
      out.write("                                                    <td>");
      out.print( item.isDonationFlag()? "Yes" : "" );
      out.write("</td>\r\n");
      out.write("                                                 ");
 } 
      out.write("\r\n");
      out.write("                                                <td>\r\n");
      out.write("                                                    \r\n");
      out.write("                                                    ");
 if (userType.equalsIgnoreCase("retailer")) { 
      out.write("\r\n");
      out.write("                                                        ");
 if (!item.isFlagged()) { 
      out.write("\r\n");
      out.write("                                                        <button type=\"button\" class=\"btn btn-info btn-xs\" onclick=\"showMarkSurplusModal(");
      out.print( item.getId());
      out.write(',');
      out.write('\'');
      out.print( item.getItemName());
      out.write("')\"> <span class=\"glyphicon glyphicon-plus\"></span> Mark as surplus</button>\r\n");
      out.write("                                                        ");
 } else{ 
      out.write("\r\n");
      out.write("                                                        <button type=\"button\" class=\"btn btn-warning btn-xs\" onclick=\"showAddDiscountModal(");
      out.print( item.getId());
      out.write(',');
      out.write('\'');
      out.print( item.getItemName());
      out.write("')\"> <span class=\"glyphicon glyphicon-usd\"></span> Add Discount</button>\r\n");
      out.write("                                                        <button type=\"button\" class=\"btn btn-danger btn-xs\" onclick=\"showAddDonationModal(");
      out.print( item.getId());
      out.write(',');
      out.write('\'');
      out.print( item.getItemName());
      out.write("')\"> <span class=\"glyphicon glyphicon-flag\"></span> Flag for Donation</button>\r\n");
      out.write("                                                        ");
 } 
      out.write("\r\n");
      out.write("                                                    ");
 } else if (userType.equalsIgnoreCase("charitable_organization")) { 
      out.write("\r\n");
      out.write("                                                        <button type=\"button\" class=\"btn btn-info btn-xs\" onclick=\"showClaimDonationModal(");
      out.print( item.getId());
      out.write(',');
      out.write('\'');
      out.print( item.getItemName());
      out.write("')\"> <span class=\"glyphicon glyphicon-plus\"></span> Claim Item</button>\r\n");
      out.write("                                                    ");
 } else{ 
      out.write("\r\n");
      out.write("                                                        <button type=\"button\" class=\"btn btn-info btn-xs\" onclick=\"showPurchaseItemModal(");
      out.print( item.getId());
      out.write(',');
      out.write('\'');
      out.print( item.getItemName());
      out.write("')\"> <span class=\"glyphicon glyphicon-plus\"></span> Purchase Item</button>\r\n");
      out.write("                                                    ");
 }  
      out.write("\r\n");
      out.write("                                                </td>\r\n");
      out.write("                                            </tr>\r\n");
      out.write("                                            ");
 }
      out.write("\r\n");
      out.write("                                        </tbody>\r\n");
      out.write("                                    </table>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                                        \r\n");
      out.write("                            ");
  if (userType.equalsIgnoreCase("charitable_organization")) { 
      out.write("  \r\n");
      out.write("                            <div class=\"panel\">\r\n");
      out.write("                                <div class=\"panel-heading\">\r\n");
      out.write("                                    <div class=\"row\">\r\n");
      out.write("                                        <div class=\"col-sm-8\">\r\n");
      out.write("                                            <h3 class=\"panel-title\"><span class=\"glyphicon glyphicon-th\"></span> Claimed Items</h3>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"panel-body\">\r\n");
      out.write("                                    <table class=\"table table-bordered table-striped\">\r\n");
      out.write("                                        <thead>\r\n");
      out.write("                                            <tr>\r\n");
      out.write("                                                <th>Item</th>\r\n");
      out.write("                                                <th>Quantity</th>\r\n");
      out.write("                                                <th>Claim Date</th>\r\n");
      out.write("                                            </tr>\r\n");
      out.write("                                        </thead>\r\n");
      out.write("                                        <tbody>\r\n");
      out.write("                                            ");
 
                                            for (ClaimedInventory item : claimedItems) {
                                            
      out.write("\r\n");
      out.write("                                            <tr id=\"item-");
      out.print( item.getId());
      out.write("\">\r\n");
      out.write("                                                <td>");
      out.print( item.getItemName());
      out.write(" </td>\r\n");
      out.write("                                                <td>");
      out.print( item.getQuantity());
      out.write(" </td>\r\n");
      out.write("                                                <td>");
      out.print( item.getClaim_date());
      out.write("</td>\r\n");
      out.write("                                            </tr>\r\n");
      out.write("                                            ");
 }
      out.write("\r\n");
      out.write("                                        </tbody>\r\n");
      out.write("                                    </table>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            ");
 }
      out.write("\r\n");
      out.write("                            \r\n");
      out.write("                            ");
  if (userType.equalsIgnoreCase("consumer")) { 
      out.write("  \r\n");
      out.write("                            <div class=\"panel\">\r\n");
      out.write("                                <div class=\"panel-heading\">\r\n");
      out.write("                                    <div class=\"row\">\r\n");
      out.write("                                        <div class=\"col-sm-8\">\r\n");
      out.write("                                            <h3 class=\"panel-title\"><span class=\"glyphicon glyphicon-th\"></span> Purchased Items</h3>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"panel-body\">\r\n");
      out.write("                                    <table class=\"table table-bordered table-striped\">\r\n");
      out.write("                                        <thead>\r\n");
      out.write("                                            <tr>\r\n");
      out.write("                                                <th>Item</th>\r\n");
      out.write("                                                <th>Quantity</th>\r\n");
      out.write("                                                <th>Purchase Date</th>\r\n");
      out.write("                                            </tr>\r\n");
      out.write("                                        </thead>\r\n");
      out.write("                                        <tbody>\r\n");
      out.write("                                            ");
 
                                            for (PurchasedInventory item : purchasedItems) {
                                            
      out.write("\r\n");
      out.write("                                            <tr id=\"item-");
      out.print( item.getId());
      out.write("\">\r\n");
      out.write("                                                <td>");
      out.print( item.getItemName());
      out.write(" </td>\r\n");
      out.write("                                                <td>");
      out.print( item.getQuantity());
      out.write(" </td>\r\n");
      out.write("                                                <td>");
      out.print( item.getPurchase_date());
      out.write("</td>\r\n");
      out.write("                                            </tr>\r\n");
      out.write("                                            ");
 }
      out.write("\r\n");
      out.write("                                        </tbody>\r\n");
      out.write("                                    </table>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"panel\">\r\n");
      out.write("                                <div class=\"panel-heading\">\r\n");
      out.write("                                    <div class=\"row\">\r\n");
      out.write("                                        <div class=\"col-sm-8\">\r\n");
      out.write("                                            <h3 class=\"panel-title\"><span class=\"glyphicon glyphicon-th\"></span> Subscriptions</h3>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"panel-body\">\r\n");
      out.write("                                    <div class=\"row\">\r\n");
      out.write("                                        <div class=\"col-sm-6\">\r\n");
      out.write("                                            <h4>Add New</h4>\r\n");
      out.write("                                            <form action=\"../SubscriptionServlet\" method=\"post\">\r\n");
      out.write("                                                <div class=\"mb-3\">\r\n");
      out.write("                                                    <label for=\"location\" class=\"form-label\">Location:</label>\r\n");
      out.write("                                                    <input type=\"text\" class=\"form-control\" id=\"location\" name=\"location\" required>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"mb-3\">\r\n");
      out.write("                                                    <label for=\"preference\" class=\"form-label\">Food Preference: <small>Leave empty if you do not want to set.</small></label>\r\n");
      out.write("                                                    <div class=\"row\">\r\n");
      out.write("                                                        <div class=\"col-sm-6\">\r\n");
      out.write("                                                            <input type=\"number\" class=\"form-control\" id=\"minPrice\" name=\"minPrice\" required placeholder=\"Minimum Price\">\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                        <div class=\"col-sm-6\">\r\n");
      out.write("                                                            <input type=\"number\" class=\"form-control\" id=\"maxPrice\" name=\"maxPrice\" required placeholder=\"Maximum Price\">\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                        <div class=\"col-sm-6\">\r\n");
      out.write("                                                            <input type=\"number\" class=\"form-control\" id=\"minQty\" name=\"minQty\" required placeholder=\"Minimum Qty\">\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                        <div class=\"col-sm-6\">\r\n");
      out.write("                                                            <input type=\"number\" class=\"form-control\" id=\"maxQty\" name=\"maxQty\" required placeholder=\"Maximum Qty\">\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"mb-3\">\r\n");
      out.write("                                                    <label class=\"form-label\">Communication Method:</label>\r\n");
      out.write("                                                    <div>\r\n");
      out.write("                                                        <input type=\"radio\" id=\"email\" name=\"communicationMethod\" value=\"email\" checked required>\r\n");
      out.write("                                                        <label for=\"email\">Email</label>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                    <div>\r\n");
      out.write("                                                        <input type=\"radio\" id=\"phone\" name=\"communicationMethod\" value=\"phone\">\r\n");
      out.write("                                                        <label for=\"phone\">Phone</label>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <button type=\"submit\" class=\"btn btn-primary\">Subscribe</button>\r\n");
      out.write("                                            </form>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"col-sm-6\">\r\n");
      out.write("                                            <table class=\"table table-bordered table-striped\">\r\n");
      out.write("                                                <thead>\r\n");
      out.write("                                                    <tr>\r\n");
      out.write("                                                        <th>Item</th>\r\n");
      out.write("                                                        <th>Quantity</th>\r\n");
      out.write("                                                        <th>Purchase Date</th>\r\n");
      out.write("                                                    </tr>\r\n");
      out.write("                                                </thead>\r\n");
      out.write("                                                <tbody>\r\n");
      out.write("                                                    ");
 
                                                    for (Subscription subscription : subscriptions) {
                                                    
      out.write("\r\n");
      out.write("                                                    <tr id=\"item-");
      out.print( subscription.getId());
      out.write("\">\r\n");
      out.write("                                                        <td>");
      out.print( subscription.getLocation());
      out.write(" </td>\r\n");
      out.write("                                                        <td>");
      out.print( subscription.getCommunicationMethod());
      out.write(" </td>\r\n");
      out.write("                                                        <td>");
      out.print( subscription.getSubsciptionDate());
      out.write("</td>\r\n");
      out.write("                                                    </tr>\r\n");
      out.write("                                                    ");
 }
      out.write("\r\n");
      out.write("                                                </tbody>\r\n");
      out.write("                                            </table>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            ");
 }
      out.write("\r\n");
      out.write("\r\n");
      out.write("                            <!-- Add Inventory Modal -->\r\n");
      out.write("                            <div class=\"modal fade\" id=\"addInventoryModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"modalLabel\" aria-hidden=\"true\">\r\n");
      out.write("                                <div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("                                    <div class=\"modal-content\">\r\n");
      out.write("                                        <div class=\"modal-header\">\r\n");
      out.write("                                            <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("                                            <h4 class=\"modal-title\">Add Item</h4>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"modal-body\">\r\n");
      out.write("                                            <form action=\"../InventoryServlet\" method=\"post\">\r\n");
      out.write("                                                <input type=\"hidden\" name=\"action\" value=\"add\">\r\n");
      out.write("                                                <div class=\"form-group\">\r\n");
      out.write("                                                    <label for=\"itemName\">Item Name</label>\r\n");
      out.write("                                                    <input type=\"text\" class=\"form-control\" name=\"itemName\" placeholder=\"Item Name\" required>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"form-group\">\r\n");
      out.write("                                                    <label for=\"quantity\">Quantity</label>\r\n");
      out.write("                                                    <input type=\"number\" class=\"form-control\" name=\"quantity\" placeholder=\"Quantity\" required>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"form-group\">\r\n");
      out.write("                                                    <label for=\"location\">Location</label>\r\n");
      out.write("                                                    <input type=\"text\" class=\"form-control\" name=\"location\" placeholder=\"Location\" required>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"form-group\">\r\n");
      out.write("                                                    <label for=\"expirationDate\">Expiration Date</label>\r\n");
      out.write("                                                    <input type=\"date\" class=\"form-control\" name=\"expirationDate\" placeholder=\"YYYY-MM-DD\" required>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"form-group\">\r\n");
      out.write("                                                    <label for=\"price\">Discount</label>\r\n");
      out.write("                                                    <input type=\"number\" class=\"form-control\" name=\"price\" placeholder=\"Discount\" required>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"row\">\r\n");
      out.write("                                                    <button type=\"submit\" class=\"btn btn-primary\" style=\"float: right;margin-right: 20px\">Add Item</button>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </form>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            \r\n");
      out.write("                        <!-- Mark as Surplus Modal -->\r\n");
      out.write("                        <div class=\"modal fade\" id=\"markSurplusModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"markSurplusModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("                          <div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("                            <div class=\"modal-content\">\r\n");
      out.write("                              <div class=\"modal-header\">\r\n");
      out.write("                                <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("                                <h5 class=\"modal-title\" id=\"markSurplusModalLabel\">Mark Item as Surplus</h5>\r\n");
      out.write("                              </div>\r\n");
      out.write("                              <div class=\"modal-body\">\r\n");
      out.write("                                <form action=\"../InventoryServlet\" method=\"post\">\r\n");
      out.write("                                  <input type=\"hidden\" id=\"markSurplusItemId\" name=\"itemId\">\r\n");
      out.write("                                  <input type=\"hidden\" name=\"action\" value=\"markSurplus\">\r\n");
      out.write("                                  <p>Are you sure you want to mark this item as surplus?</p>\r\n");
      out.write("                                  <button type=\"submit\" class=\"btn btn-primary\">Confirm</button>\r\n");
      out.write("                                </form>\r\n");
      out.write("                              </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        \r\n");
      out.write("                        <!-- Add Quantity Modal -->\r\n");
      out.write("                        <div class=\"modal fade\" id=\"addQuantityModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"addQuantityModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("                          <div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("                            <div class=\"modal-content\">\r\n");
      out.write("                              <div class=\"modal-header\">\r\n");
      out.write("                                <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("                                <h5 class=\"modal-title\" id=\"addQuantityModalLabel\">Add Quantity</h5>\r\n");
      out.write("                              </div>\r\n");
      out.write("                              <div class=\"modal-body\">\r\n");
      out.write("                                <form action=\"../InventoryServlet\" method=\"post\">\r\n");
      out.write("                                  <div class=\"form-group\">\r\n");
      out.write("                                    <label for=\"currentQty\">Current Qty:</label>\r\n");
      out.write("                                    <input type=\"text\" class=\"form-control\" id=\"currentQty\" readonly>\r\n");
      out.write("                                  </div>\r\n");
      out.write("                                  <div class=\"form-group\">\r\n");
      out.write("                                    <label for=\"quantityToAdd\">Quantity to Add:</label>\r\n");
      out.write("                                    <input type=\"number\" class=\"form-control\" id=\"quantityToAdd\" name=\"quantityToAdd\" required>\r\n");
      out.write("                                  </div>\r\n");
      out.write("                                  <div class=\"form-group\">\r\n");
      out.write("                                    <label for=\"totalQty\">Total Quantity:</label>\r\n");
      out.write("                                    <input type=\"text\" class=\"form-control\" id=\"totalQty\" readonly>\r\n");
      out.write("                                    <input type=\"hidden\" id=\"addQuantityItemId\" name=\"itemId\">\r\n");
      out.write("                                    <input type=\"hidden\" name=\"action\" value=\"addQuantity\">\r\n");
      out.write("                                  </div>\r\n");
      out.write("                                  <button type=\"submit\" class=\"btn btn-primary\">Add Quantity</button>\r\n");
      out.write("                                </form>\r\n");
      out.write("                              </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <!-- Flag Discount Modal -->\r\n");
      out.write("                        <div class=\"modal fade\" id=\"flagDiscountModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"flagDiscountModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("                          <div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("                            <div class=\"modal-content\">\r\n");
      out.write("                              <div class=\"modal-header\">\r\n");
      out.write("                                <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("                                <h5 class=\"modal-title\" id=\"flagDiscountModalLabel\">Flag Discount</h5>\r\n");
      out.write("                              </div>\r\n");
      out.write("                              <div class=\"modal-body\">\r\n");
      out.write("                                <form action=\"../InventoryServlet\" method=\"post\">\r\n");
      out.write("                                  <div class=\"form-group\">\r\n");
      out.write("                                    <label for=\"originalPrice\">Original Price:</label>\r\n");
      out.write("                                    <input type=\"text\" class=\"form-control\" id=\"originalPrice\" readonly>\r\n");
      out.write("                                  </div>\r\n");
      out.write("                                  <div class=\"form-group\">\r\n");
      out.write("                                    <label for=\"discountAmount\">Discount Amount:</label>\r\n");
      out.write("                                    <input type=\"number\" class=\"form-control\" id=\"discountAmount\" name=\"discountAmount\" required oninput=\"calculateDiscountedPrice()\">\r\n");
      out.write("                                  </div>\r\n");
      out.write("                                  <div class=\"form-group\">\r\n");
      out.write("                                    <label for=\"discountedPrice\">Discounted Price:</label>\r\n");
      out.write("                                    <input type=\"text\" class=\"form-control\" id=\"discountedPrice\" readonly>\r\n");
      out.write("                                    <input type=\"hidden\" id=\"flagDiscountItemId\" name=\"itemId\">\r\n");
      out.write("                                    <input type=\"hidden\" name=\"action\" value=\"flagDiscount\">\r\n");
      out.write("                                  </div>\r\n");
      out.write("                                  <button type=\"submit\" class=\"btn btn-primary\">Apply Discount</button>\r\n");
      out.write("                                </form>\r\n");
      out.write("                              </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        \r\n");
      out.write("                        \r\n");
      out.write("                        <!-- Mark for Donation Modal -->\r\n");
      out.write("                        <div class=\"modal fade\" id=\"markDonationModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"markDonationModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("                          <div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("                            <div class=\"modal-content\">\r\n");
      out.write("                              <div class=\"modal-header\">\r\n");
      out.write("                                <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("                                <h5 class=\"modal-title\" id=\"markDonationModalLabel\">Mark Item for Donation</h5>\r\n");
      out.write("                              </div>\r\n");
      out.write("                              <div class=\"modal-body\">\r\n");
      out.write("                                <form action=\"../InventoryServlet\" method=\"post\">\r\n");
      out.write("                                  <input type=\"hidden\" id=\"markDonationItemId\" name=\"itemId\">\r\n");
      out.write("                                  <input type=\"hidden\" name=\"action\" value=\"markForDonation\">\r\n");
      out.write("                                  <p>Are you sure you want to mark this item for donation?</p>\r\n");
      out.write("                                  <button type=\"submit\" class=\"btn btn-primary\">Confirm</button>\r\n");
      out.write("                                </form>\r\n");
      out.write("                              </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <!-- Claim Donation Modal -->\r\n");
      out.write("                        <div class=\"modal fade\" id=\"claimDonationModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"claimDonationModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("                          <div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("                            <div class=\"modal-content\">\r\n");
      out.write("                              <div class=\"modal-header\">\r\n");
      out.write("                                <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("                                <h5 class=\"modal-title\" id=\"claimDonationModalLabel\">Claim Item for Donation</h5>\r\n");
      out.write("                              </div>\r\n");
      out.write("                              <div class=\"modal-body\">\r\n");
      out.write("                                <form action=\"../InventoryServlet\" method=\"post\">\r\n");
      out.write("                                  <input type=\"hidden\" id=\"claimDonationItemId\" name=\"itemId\">\r\n");
      out.write("                                  <input type=\"hidden\" name=\"action\" value=\"claimAsDonation\">\r\n");
      out.write("                                  <p>Are you sure you want to claim this item for donation?</p>\r\n");
      out.write("                                  <button type=\"submit\" class=\"btn btn-primary\">Confirm</button>\r\n");
      out.write("                                </form>\r\n");
      out.write("                              </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        \r\n");
      out.write("                        <!-- Purchase Item Modal -->\r\n");
      out.write("                        <div class=\"modal fade\" id=\"purchaseItemModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"purchaseItemModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("                          <div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("                            <div class=\"modal-content\">\r\n");
      out.write("                              <div class=\"modal-header\">\r\n");
      out.write("                                <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("                                <h5 class=\"modal-title\" id=\"purchaseItemModalLabel\">Purchase Item</h5>\r\n");
      out.write("                              </div>\r\n");
      out.write("                              <div class=\"modal-body\">\r\n");
      out.write("                                <form action=\"../InventoryServlet\" method=\"post\">\r\n");
      out.write("                                  <input type=\"hidden\" id=\"purchaseItemId\" name=\"itemId\">\r\n");
      out.write("                                  <input type=\"hidden\" name=\"action\" value=\"purchaseItem\">\r\n");
      out.write("                                  <div class=\"form-group\">\r\n");
      out.write("                                    <label for=\"quantityToAdd\">Select Qty:</label>\r\n");
      out.write("                                    <input type=\"number\" class=\"form-control\" id=\"quantityToPurchase\" name=\"quantityToPurchase\" value=\"1\" required>\r\n");
      out.write("                                  </div>\r\n");
      out.write("                                  <button type=\"submit\" class=\"btn btn-primary\">Confirm</button>\r\n");
      out.write("                                </form>\r\n");
      out.write("                              </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </body>\r\n");
      out.write("                    <script>\r\n");
      out.write("                        function showMarkSurplusModal(itemId, itemName) {\r\n");
      out.write("                          $('#markSurplusModalLabel').text(`Flag `+itemName+' as surplus');\r\n");
      out.write("                          $('#markSurplusItemId').val(itemId);\r\n");
      out.write("                          $('#markSurplusModal').modal('show');\r\n");
      out.write("                        }\r\n");
      out.write("                        function showAddDonationModal(itemId, itemName){\r\n");
      out.write("                          $('#markDonationModalLabel').text(`Mark `+itemName+' for donation');\r\n");
      out.write("                          $('#markDonationItemId').val(itemId);\r\n");
      out.write("                          $('#markDonationModal').modal('show');\r\n");
      out.write("                        }\r\n");
      out.write("                        function showClaimDonationModal(itemId, itemName){\r\n");
      out.write("                            $('#claimDonationModalLabel').text(`Claim `+itemName+' as donation');\r\n");
      out.write("                            $('#claimDonationItemId').val(itemId);\r\n");
      out.write("                            $('#claimDonationModal').modal('show');\r\n");
      out.write("                          }\r\n");
      out.write("                        function showPurchaseItemModal(itemId, itemName){\r\n");
      out.write("                          $('#purchaseItemModalLabel').text(`Purchase `+itemName);\r\n");
      out.write("                          $('#purchaseItemId').val(itemId);\r\n");
      out.write("                          var qty = $(\"#item-\" + itemId).find(\"td:eq(1)\").text();\r\n");
      out.write("                          $(\"input\").attr({\"max\" : qty,\"min\" : 1});\r\n");
      out.write("                          $('#purchaseItemModal').modal('show');\r\n");
      out.write("                        }\r\n");
      out.write("\r\n");
      out.write("                        // Show the Add Quantity Modal and populate it\r\n");
      out.write("                        function showAddQuantityModal(itemId, itemName) {\r\n");
      out.write("                          $('#addQuantityModalLabel').text(`Add Quantity for `+itemName);\r\n");
      out.write("                          $('#addQuantityItemId').val(itemId);\r\n");
      out.write("                          var currentQty = $(\"#item-\" + itemId).find(\"td:eq(1)\").text();\r\n");
      out.write("                          $('#currentQty').val(currentQty);\r\n");
      out.write("                          $('#addQuantityModal').modal('show');\r\n");
      out.write("                        }\r\n");
      out.write("\r\n");
      out.write("                        // Show the Flag Discount Modal and populate it\r\n");
      out.write("                        function showAddDiscountModal(itemId, itemName) {\r\n");
      out.write("                          $('#flagDiscountModalLabel').text(`Set Discount for `+itemName);\r\n");
      out.write("                          $('#flagDiscountItemId').val(itemId);\r\n");
      out.write("                          var originalPrice = parseFloat($(\"#item-\" + itemId).find(\"td:eq(3)\").text());\r\n");
      out.write("                          $('#originalPrice').val(originalPrice);\r\n");
      out.write("                          $('#flagDiscountModal').modal('show');\r\n");
      out.write("                        }\r\n");
      out.write("                        // Calculate the new qty on input change\r\n");
      out.write("                        $('#quantityToAdd').on('input', function() {\r\n");
      out.write("                            calculateTotalQty();\r\n");
      out.write("                        });\r\n");
      out.write("                        \r\n");
      out.write("                        function calculateTotalQty() {\r\n");
      out.write("                            var currentQty = parseInt($(\"#item-\" + $('#addQuantityItemId').val()).find(\"td:eq(1)\").text());\r\n");
      out.write("                            var quantityToAdd = parseInt($('#quantityToAdd').val());\r\n");
      out.write("                            \r\n");
      out.write("                            var totalQty = quantityToAdd + currentQty;\r\n");
      out.write("                            $('#totalQty').val(totalQty);\r\n");
      out.write("                        }\r\n");
      out.write("                        \r\n");
      out.write("                        // Calculate the discounted price on input change\r\n");
      out.write("                        $('#discountAmount').on('input', function() {\r\n");
      out.write("                            calculateDiscountedPrice();\r\n");
      out.write("                        });\r\n");
      out.write("\r\n");
      out.write("                        function calculateDiscountedPrice() {\r\n");
      out.write("                            var originalPrice = parseFloat($(\"#item-\" + $('#flagDiscountItemId').val()).find(\"td:eq(3)\").text());\r\n");
      out.write("                            var discount = parseFloat($('#discountAmount').val());\r\n");
      out.write("                            var discountedPrice = originalPrice - discount;\r\n");
      out.write("                            $('#discountedPrice').val(discountedPrice.toFixed(2));\r\n");
      out.write("                        }\r\n");
      out.write("                         $('#toggleExpiresInAweek').click(function() {\r\n");
      out.write("                            if ($(this).is(':checked')) {\r\n");
      out.write("                                $('tbody tr').hide(); // Hide all rows\r\n");
      out.write("                                $('.expiresInAweek_item').show(); // Show only rows with the surplus_item class\r\n");
      out.write("                            } else {\r\n");
      out.write("                                $('tbody tr').show(); // Show all rows\r\n");
      out.write("                            }\r\n");
      out.write("                        });\r\n");
      out.write("                        </script>\r\n");
      out.write("                    </html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
